### ISSUE TITLE
How can I start thin with multiple servers

### ISSUE THREAD

**Issue by shlima** [kostya/eye#122]
I have a thin config
```yml
---
pid: tmp/pids/thin.web.pid
socket: tmp/sockets/thin.web.sock
timeout: 20
wait: 20
log: log/thin.web.log
max_conns: 1024
environment: production
max_persistent_conns: 512
servers: 2
threaded: false
daemonize: true
tag: thin.web
```

Eye config for the eye is following:

```ruby
group 'web' do
    process 'thin_web' do
      pid_file 'tmp/pids/thin.web.pid'
      start_command "bundle exec thin -C #{working_dir}/config/thin.web.yml start"
      stop_command 'kill -QUIT {{PID}}'
      restart_command 'kill -USR1 {{PID}}'

      start_timeout 60.seconds
    end
end
```

Eye's strdout log is the following 
```
Starting server on tmp/sockets/thin.web.0.sock ... 
Starting server on tmp/sockets/thin.web.1.sock ... 
Starting server on tmp/sockets/thin.web.0.sock ... 
/Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/daemonizing.rb:171:in `remove_stale_pid_file': tmp/pids/thin.web.0.pid already exists, seems like it's already running (process ID: 7584). Stop the process or delete tmp/pids/thin.web.0.pid. (Thin::PidFileExist)
from /Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/daemonizing.rb:43:in `daemonize'
from /Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:62:in `start'
from /Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
from /Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
from /Users/alex/.rvm/gems/ruby-2.2.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
from /Users/alex/.rvm/gems/ruby-2.2.1/bin/thin:23:in `load'
from /Users/alex/.rvm/gems/ruby-2.2.1/bin/thin:23:in `<main>'
from /Users/alex/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
from /Users/alex/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

It seems that the Eye tries to start thin multiple times?
